spring:
  application:
    name: vue_login_server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/vue_login?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: admin
server:
  port: 8087
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
  servlet:
    context-path: /vue_login
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codervibe.vue_login_server.model


logging:
  level:
    root: info
    com.codervibe.vue_login_server: info
    com.codervibe.vue_login_server.mapper: debug
  file:
    path: ./vue_login_server/log

